openapi: 3.0.1
info:
  title: My App
  description: A Phoenix App
#   termsOfService: Pending
#   contact:
#     email: 
#   license:
#     name: MIT License
#     url: https://opensource.org/licenses/MIT
  version: 0.0.1
# externalDocs:
#   description:
#   url: 
servers:
- url: /v1
paths:
  /registrations:
    post:
      tags:
      - Registration
      summary: Create an registration
      operationId: sign_up
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: bad_request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '400'
                errors: [{
                  detail: 'Bad request'
                }]
        '422':
          description: unprocessable_entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataError'
              example:
                status: 422
                errors: [{
                  detail: 'Email is already in use',
                }]
      x-codegen-request-body-name: body
  /sessions:
    post:
      tags:
      - Session
      summary: Create user session
      operationId: sign_in
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: bad_request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '400'
                errors: [{
                  detail: 'Bad request'
                }]
        '401':
          description: unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 422
                errors: [{
                  detail: 'Bad credentials',
                }]
      x-codegen-request-body-name: body
    delete:
      security:
        - cookieAuth: []
      tags:
      - Session
      summary: Destroy user session
      operationId: sign_out
      responses:
        '204':
          description: no_content
        '400':
          description: bad_request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '400'
                errors: [{
                  detail: 'Bad request'
                }]
        '401':
          description: unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 422
                errors: [{
                  detail: 'Bad credentials',
                }]
      x-codegen-request-body-name: body
  /users:
    post:
      security:
        - cookieAuth: []
      tags:
      - User
      summary: Create users
      operationId: create_users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: bad_request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '400'
                errors: [{
                  detail: 'Bad request'
                }]
        '422':
          description: unprocessable_entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        detail: 
                          type: string
                  failed_index:
                    type: number
                  failed_email:
                    type: string
                    format: email
      x-codegen-request-body-name: body
    get:
      security:
        - cookieAuth: []
      tags:
      - User
      summary: List users
      operationId: get_list_of_users
      parameters:
      - name: items
        in: query
        schema:
          type: integer
      - name: page
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                  items:
                    type: integer
                  count:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '400':
          description: bad_request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '400'
                errors: [{
                  detail: 'Bad request'
                }]
        '404':
          description: not_found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '404'
                errors: [{
                  detail: 'Not found'
                }]
        '422':
          description: unprocessable_entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataError'
              example:
                status: 422
                errors: [{
                  detail: 'Email is already in use',
                }]
  /users/{user_id}:
    get:
      security:
        - cookieAuth: []
      tags:
      - User
      summary: Show info of an user
      operationId: get_user_by_id
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: bad_request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: not_found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      security:
        - cookieAuth: []
      tags:
      - User
      summary: Update user
      operationId: update_user_by_id
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: bad_request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '400'
                errors: [{
                  detail: 'Bad request'
                }]
        '404':
          description: not_found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '404'
                errors: [{
                  detail: 'Not found'
                }]
        '422':
          description: unprocessable_entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataError'
              example:
                status: 422
                errors: [{
                  detail: 'Email is already in use',
                }]
      x-codegen-request-body-name: body
  /users/delete:
    post:
      security:
        - cookieAuth: []
      tags:
      - User
      summary: Delete users
      operationId: delete_user_by_ids
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - users
              properties:
                users:
                  type: array
                  items:
                    type: object
                    required:
                      - id
                    properties:
                      id:
                        type: string
        required: true
      responses:
        '204':
          description: no_content
        '400':
          description: bad_request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '400'
                errors: [{
                  detail: 'Bad request'
                }]
        '404':
          description: not_found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: '404'
                errors: [{
                  detail: 'Not found'
                }]
        '422':
          description: unprocessable_entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataError'
              example:
                status: 422
                errors: [{
                  detail: 'Email is already in use',
                }]
      x-codegen-request-body-name: body
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          writeOnly: true
        inserted_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      xml:
        name: User
    Error:
      type: object
      required:
        - status
        - errors
      properties:
        status:
          type: string
        errors:
          type: array
          items:
            required:
              - detail
            properties:
              detail: 
                type: string
    DataError:
      type: object
      required:
        - status
        - errors
      properties:
        status:
          type: string
        errors:
          type: array
          items:
            required:
              - detail
            properties:
              detail: 
                type: string
  securitySchemes:
    cookieAuth:         # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: _my_app_key  # cookie name      
  #   bearerAuth:
  #     type: http
  #     scheme: bearer
  #     bearerFormat: JWT
  #     description: To be implemented later
